# Site settings
author: Anthony Hernandez
title: A RUBY in the Rough
header-img: img/home-bg.png
email: anthonyh2020@gmail.com
copyright_name: Anthony Hernandez
description: > # this means to ignore newlines until "baseurl:"
  Going all the way up!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Tonito135

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
